name: stream_feed_dart
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  json_annotation: ^3.0.1
  rxdart: ^0.24.1
  dio: ^3.0.10
  logging: ^0.11.4

dev_dependencies:
  test: ^1.15.4
  build_runner: ^1.10.0
  json_serializable: ^3.4.1
  pedantic: ^1.9.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
