name: faye_dart
description: Faye is a publish/subscribe messaging protocol that is built on the Bayeux protocol, a messaging system utilized for transporting asynchronous messages over HTTP.
version: 0.0.1
homepage: https://getstream.io/

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  web_socket_channel: ^2.0.0
  equatable: ^2.0.0
  logging: ^1.0.1

dev_dependencies:
  test: ^1.16.8
  mocktail: ^0.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec