name: faye_dart
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  web_socket_channel: ^2.0.0
  rxdart: ^0.26.0

dev_dependencies:
  test: ^1.16.7

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec