name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        channel:
          - dev
          # - stable

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.channel }}

      - name: Add pub cache bin to PATH
        run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Add pub cache to PATH
        run: echo "PUB_CACHE="$HOME/.pub-cache"" >> $GITHUB_ENV
        
      - name: Add feed secret to env
        run: echo secrets.SECRET >> $secret
      
      - name: Add feed appId to env
        run: echo secrets.APPID >> $appId
        
      - name: Add feed apiKey to env
        run: echo secrets.APIKEY >> $apiKey

      - run: dart pub global activate melos

      - name: Install dependencies
        run: melos bootstrap

      - name: Check format
        run: melos run format

      - name: Generate models
        run: melos run generate
      
      - name: Analyze
        run: melos run analyze

      - name: Run tests
        run: melos run test

      - name: Post Codecov report
        run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
      - uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          path: packages/stream_feed/coverage/lcov.info
          min_coverage: 82  
      - uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          path: packages/faye_dart/coverage/lcov.info
          min_coverage: 26
